ci:
  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit suggestions'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        name: End-of-file fixer
      - id: trailing-whitespace
        name: Remove trailing whitespaces
      - id: check-toml
        name: Check toml
      - id: check-yaml
        name: Check yaml
        exclude: |
          (?x)^(
              conda/pytorch-geometric/meta.yaml|
              conda/pyg/meta.yaml
          )$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.30.0
    hooks:
      - id: yamllint
        name: Lint yaml
        args: [-d, '{extends: default, rules: {line-length: disable, document-start: disable, truthy: {level: error}, braces: {max-spaces-inside: 1}}}']

  # - repo: https://github.com/regebro/pyroma
  #   rev: "4.2"
  #   hooks:
  #     - id: pyroma
  #       name: Check packaging
  #       args: [--min=10, .]

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        name: Format code
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Sort imports

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
