language: shell

os:
  - linux
  - osx
  - windows

env:
  jobs:
    - TORCH_VERSION=1.4.0 PYTHON_VERSION=3.8 IDX=cpu
    - TORCH_VERSION=1.5.0 PYTHON_VERSION=3.8 IDX=cpu

install:
  - source script/conda.sh
  - conda create --yes -n test python="${PYTHON_VERSION}"
  - source activate test
  - conda install pytorch=${TORCH_VERSION} torchvision ${TOOLKIT} -c pytorch --yes
  - pip install torch-scatter==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-sparse==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-cluster==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install torch-spline-conv==latest+${IDX} -f https://pytorch-geometric.com/whl/torch-${TORCH_VERSION}.html
  - pip install cython
  - git clone https://github.com/the-virtual-brain/tvb-geodesic /tmp/gdist
  - cd /tmp/gdist && python setup.py install && cd -
  - pip install scikit-image
  - pip install trimesh
  - pip install flake8 codecov
  - pip install sphinx sphinx_rtd_theme
  - python setup.py install
script:
  - flake8 .
  - python setup.py test
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cd docs && make clean && make html && cd ..; fi
after_success:
  - codecov
notifications:
  email: false
