jobs:
  include:
    - os: linux
      language: python
      python: 3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - CC=gcc-5
        - CXX=g++-5
install:
  - pip install numpy
  - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install torch-scatter==latest+cpu -f http://pytorch-scatter.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-scatter.s3-website.eu-central-1.amazonaws.com
  - pip install torch-sparse==latest+cpu -f http://pytorch-sparse.s3-website.eu-central-1.amazonaws.com/whl/torch-1.4.0.html --trusted-host pytorch-sparse.s3-website.eu-central-1.amazonaws.com
  - pip install torch-cluster
  - pip install torch-spline-conv
  - pip install cython && pip install gdist
  - pip install trimesh
  - pip install pycodestyle
  - pip install flake8
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - python -c "import torch; print(torch.__version__)"
  - pycodestyle .
  - flake8 .
  - python setup.py install
  - python setup.py test
  - cd docs && make clean && make html && cd ..
after_success:
  - codecov
notifications:
  email: false
