name: Building Conda

on: [workflow_dispatch]

jobs:

  conda-build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, macos-10.15, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        torch-version: [1.8.0, 1.9.0]
        cuda-version: ['cpu', 'cu101', 'cu102', 'cu111']
        exclude:
          - torch-version: 1.9.0
            cuda-version: 'cu101'
          - os: macos-10.15
            cuda-version: 'cu101'
          - os: macos-10.15
            cuda-version: 'cu102'
          - os: macos-10.15
            cuda-version: 'cu111'
          - os: windows-latest
            cuda-version: 'cu101'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Conda for Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Conda packages
        run: |
          conda install conda-build conda-verify --yes
        shell:
          bash -l {0}

      - name: Build Conda package
        run: |
          ./conda/pytorch-geometric/build_conda.sh ${{ matrix.python-version }} ${{ matrix.torch-version }} ${{ matrix.cuda-version }}
        shell:
          bash -l {0}

      - name: Publish Conda package
        run: |
          conda install anaconda-client --yes
          anaconda upload --force --label main $HOME/conda-bld/*/*.tar.bz2
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        shell:
          bash -l {0}
