name: Changelog Enforcer

on:  # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:

  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Enforce changelog entry
        uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: 'skip-changelog'
