name: Documentation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  make_html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 40

      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            benchmark/**
            conda/**
            docker/**
            examples/**
            graphgym/**
            README.md
            CHANGELOG.md

      - name: Setup packages
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: ./.github/actions/setup
        with:
          full_install: false

      - name: Install main package
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          uv pip install nbsphinx
          uv pip install git+https://github.com/pyg-team/pyg_sphinx_theme.git
          uv pip install -e .

      - name: Build documentation
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        working-directory: ./docs
        run: |
          uv run --no-project sphinx-build -M html "source" "build" -W  # Fail on warning.
