name: Minimal Installation

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:

  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 40

      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            benchmark/**
            conda/**
            docker/**
            docs/**
            examples/**
            graphgym/**
            CHANGELOG.md

      - name: Setup packages
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: ./.github/actions/setup

      - name: Install main package
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          pip install -e .[test]

      - name: Test imports
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          python -c "import torch_geometric"
          python -c "import torch_geometric.datasets"
          python -c "import torch_geometric.nn"
          python -c "import torch_geometric.graphgym"

      - name: Run tests
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          pytest
