name: PR Labeler

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:

  assign-labels:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Add PR labels
        uses: actions/labeler@v6
        continue-on-error: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  assign-author:
    if: github.repository == 'pyg-team/pytorch_geometric'
    runs-on: ubuntu-latest

    steps:
      - name: Add PR author
        uses: samspills/assign-pr-to-author@v1.0
        continue-on-error: true
        if: github.event_name == 'pull_request'
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
