name: Testing distributed PyG

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  dist_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 40

      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v46
        with:
          files: |
            torch_geometric/distributed/**
            test/distributed/**

      - name: Setup packages
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: ./.github/actions/setup

      - name: Install main package
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          uv pip install -e ".[test]"

      - name: Check installation
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          uv run --no-project python -c "import torch; print('PyTorch:', torch.__version__)"
          uv run --no-project python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
          uv run --no-project python -c "import torch; print('CUDA:', torch.version.cuda)"
        shell: bash

      - name: Run tests
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        timeout-minutes: 10
        run: |
          DIST_TEST=1 uv run --no-project pytest test/distributed --durations 10
        shell: bash
