name: Testing nightly PyTorch

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ startsWith(github.ref, 'refs/pull/') || github.run_number }}  # yamllint disable-line
  # Only cancel intermediate builds if on a PR:
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  nightly_pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 40

      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v47
        with:
          files: |
            benchmark/**
            conda/**
            docker/**
            docs/**
            examples/**
            graphgym/**
            README.md
            CHANGELOG.md

      - name: Setup packages
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: ./.github/actions/setup
        with:
          torch-version: nightly

      - name: Install main package
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          uv pip install -e ".[test]"

      - name: Check installation
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          uv run --no-project python -c "import torch; print('PyTorch:', torch.__version__)"
          uv run --no-project python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
          uv run --no-project python -c "import torch; print('CUDA:', torch.version.cuda)"
        shell: bash

      - name: Run tests
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        timeout-minutes: 15
        run: |
          uv run --no-project pytest --durations 10
